### ISSUE TITLE
aarch_64 / M1 not supported

### ISSUE THREAD

**Issue by maxandersen** [quarkiverse/quarkus-ngrok#37]
when using jbang with ngrok it manages to work on my M1 mac - but when running via mvn I get this error:

```
2022-12-24 00:35:26,087 WARN  [io.qua.dep.dev.IsolatedDevModeMain] (main) Unable to invoke 'afterFirstStart' of class io.quarkiverse.ngrok.deployment.NgrokDevModeListener: java.lang.RuntimeException: Unsupported architecture 'aarch_64'
	at io.quarkiverse.ngrok.deployment.NgrokDevModeListener.determineArchString(NgrokDevModeListener.java:168)
	at io.quarkiverse.ngrok.deployment.NgrokDevModeListener.createDownloadURL(NgrokDevModeListener.java:142)
	at io.quarkiverse.ngrok.deployment.NgrokDevModeListener.determineDownloadURL(NgrokDevModeListener.java:137)
	at io.quarkiverse.ngrok.deployment.NgrokDevModeListener.startNgrokIfNecessary(NgrokDevModeListener.java:74)
	at io.quarkiverse.ngrok.deployment.NgrokDevModeListener.afterFirstStart(NgrokDevModeListener.java:42)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:149)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:447)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:59)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:149)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:104)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
```

**Comment by maxandersen** [comment]
whats weird is it working using jbang:

```
2022-12-24 00:24:29,816 INFO  [io.qua.ngr.dep.NgrokDevModeListener] (ngrok starter thread) Attempting to download ngrok from https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-darwin-amd64.zip
2022-12-24 00:24:40,321 INFO  [io.qua.ngr.dep.NgrokDevModeListener] (ngrok starter thread) ngrok downloaded and extracted to /Users/manderse/.quarkus/ngrok
```

**Comment by geoand** [comment]
Should be an easy fix
