### ISSUE TITLE
Quarkus 3.6.0 Error

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-ngrok#82]
Running ngrok 1.1.0 with Quarkus 3.6.0 throws this error..

```
2023-12-02 12:19:08,593 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: Failed to load steps from class io.quarkiverse.ngrok.deployment.NgrokProcessor
        at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:164)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:107)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:330)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:251)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:112)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:433)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:55)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:138)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:93)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: java.lang.NoClassDefFoundError: io/quarkus/devconsole/spi/DevConsoleRuntimeTemplateInfoBuildItem
```

Does a newer version of ngrok need to be released?

**Comment by geoand** [comment]
I guess so, I'll do that on Monday

**Comment by melloware** [comment]
I just built the 999-SNAPSHOT and its working but the Dev UI card has an issue I see this

```
12:24:56 INFO  [io.qu.ng.de.NgrokDevModeListener] (ngrok starter thread) ngrok is running and its web interface can be accessed at: 'http://localhost:4040'
12:24:56 INFO  [io.qu.ng.de.NgrokDevModeListener] (ngrok starter thread) The application can be accessed publicly over the internet using: 'http://6e7d-68-81-186-238.ngrok-free.app'
12:24:56 WARN  [io.qu.ng.de.NgrokDevModeListener] (ngrok starter thread) Unable to setup the DevUI with ngrok info
```

Want me to open a different ticket?

**Comment by geoand** [comment]
Thanks for checking.

No need for a new issue, this one is fine
